customhost = "databasefinalproject.cqvn6gf20qmy.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "cycuawsclass"
customdb = "employee"
custombucket = "10720125-mybucket"
customregion = "us-east-1b"
